### ISSUE TITLE
Submitting an exercise without TMC plugin

### ISSUE THREAD

**Issue by Maktm** [cybersecuritybase/cybersecuritybase.github.io#9]
How can I submit my exercise without using the TMC plugin? On the course it says:

'submitting them means sending them to the server as a zip.'

But that's very vague.

**Comment by chokepoint** [comment]
Visit https://tmc.mooc.fi/org/mooc/courses/173 after logging in and submit accordingly.

**Comment by Maktm** [comment]
My mistake for being lazy. Closed.

**Comment by Maktm** [comment]
Submitting seems to fail. I get the message --

"We're sorry, but something went wrong.

Please ask an administrator to look at the server logs."

**Comment by nygrenh** [comment]
@Maktm I'm the server administrator. Can you provide the zip you're trying to send?

**Comment by Maktm** [comment]
It doesn't seem to upload any files without that error message. Here's the first file I tried:

https://www.sendspace.com/file/5abm4c

**Comment by nygrenh** [comment]
@Maktm thanks, figured out what the problem was. The submission errored because it could't find a `src` folder in the zip. We expect that the project structure is similar to the template.

Also, you shouldn't include only the controller in your submission. Our automated system cannot test the exercise if you remove all the other files from the project because it's hard to run a program without all of its parts.

The easiest way for successfully submitting a zip from the web ui  is:
1. Download the project template zip from the exercise page
2. Extract it
3. Edit the extracted files with your solution
4. Run the tests to ensure your solution is correct
5. Re-zip the whole directory structure again (so that it includes the same stuff that were in the original zip)
6. Submit your new zip
7. Wait for test results

Hope this cleared up the confusion.

**Comment by Maktm** [comment]
Makes sense. Thanks for the help!

Edit:

It may help to add a note on the site describing this.

**Comment by nygrenh** [comment]
Yeah, I'll look into making this process more obvious when I have the time.
